version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: vehicles-manager
      MYSQL_USER: usr
      MYSQL_PASSWORD: pswd
      MYSQL_ROOT_PASSWORD: pswd
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
volumes:
  my-db:

