/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pooavanzadog62.vistas;

import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pooavanzadog62.clases.clsAutomovil;
import pooavanzadog62.clases.clsAvion;
import pooavanzadog62.clases.clsVehiculo;
import pooavanzadog62.controlador.ctrlVehiculo;


/**
 *
 * @author samur
 */
public class AdminVehiculos extends javax.swing.JFrame {
    ctrlVehiculo ctrlVehiculo;
    LinkedList<clsVehiculo> vehiculos = new LinkedList<>();
    /**
     * Creates new form AdminVehiculos
     */
    public AdminVehiculos() {
        initComponents();
        this.ctrlVehiculo = new ctrlVehiculo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsListaVehiculos = new javax.swing.JList<>();
        panel2 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textImprontaVehiculo = new javax.swing.JTextField();
        textPasajerosVehiculo = new javax.swing.JTextField();
        textCantidadCombustibleVehiculo = new javax.swing.JTextField();
        cbEstadoVehiculo = new javax.swing.JComboBox<>();
        btCrearVehiculo = new javax.swing.JButton();
        btConsultarVehiculo = new javax.swing.JButton();
        btEditarVehiculo = new javax.swing.JButton();
        btEliminarVehiculo = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textImprontaAvion = new javax.swing.JTextField();
        textPasajerosAvion = new javax.swing.JTextField();
        textCantidadCombustibleAvion = new javax.swing.JTextField();
        cbEstadoAvion = new javax.swing.JComboBox<>();
        cbTipoCombustibleAvion = new javax.swing.JComboBox<>();
        btCrearAvion = new javax.swing.JButton();
        btConsultarAvion = new javax.swing.JButton();
        btEditarAvion = new javax.swing.JButton();
        btEliminarAvion = new javax.swing.JButton();
        panel4 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Administrador Vehículos");

        lsListaVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lsListaVehiculos);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista Vehiculos", panel1);

        jLabel2.setText("Impronta Chasis");

        jLabel3.setText("Pasajeros");

        jLabel4.setText("Combustible");

        jLabel5.setText("Estado vehículo");

        textCantidadCombustibleVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCantidadCombustibleVehiculoActionPerformed(evt);
            }
        });

        cbEstadoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En funcionamiento", "Averiado", "Reparado", "Necesita revisión" }));

        btCrearVehiculo.setText("Crear Vehiculo");
        btCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearVehiculoActionPerformed(evt);
            }
        });

        btConsultarVehiculo.setText("Consultar Vehículo");
        btConsultarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarVehiculoActionPerformed(evt);
            }
        });

        btEditarVehiculo.setText("Editar Vehículo");
        btEditarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarVehiculoActionPerformed(evt);
            }
        });

        btEliminarVehiculo.setText("Eliminar Vehículo");
        btEliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(57, 57, 57)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEstadoVehiculo, 0, 108, Short.MAX_VALUE)
                    .addComponent(textCantidadCombustibleVehiculo)
                    .addComponent(textPasajerosVehiculo)
                    .addComponent(textImprontaVehiculo))
                .addGap(55, 55, 55)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btConsultarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCrearVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEditarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textImprontaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCrearVehiculo))
                .addGap(20, 20, 20)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textPasajerosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultarVehiculo))
                .addGap(29, 29, 29)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textCantidadCombustibleVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditarVehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbEstadoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminarVehiculo))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Vehiculos", panel2);

        jLabel6.setText("Impronta Chasis");

        jLabel7.setText("Pasajeros");

        jLabel8.setText("Cantidad Combustible");
        jLabel8.setToolTipText("");

        jLabel9.setText("Estado Vehículo");

        jLabel10.setText("Tipo Combustible");

        textImprontaAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textImprontaAvionActionPerformed(evt);
            }
        });

        cbEstadoAvion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En funcionamiento", "Averiado", "Reparado", "En mantenimiento", "Require revision" }));

        cbTipoCombustibleAvion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina 100", "Gasolina 130", " " }));

        btCrearAvion.setText("Crear Avión");
        btCrearAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearAvionActionPerformed(evt);
            }
        });

        btConsultarAvion.setText("Consultar Avión");
        btConsultarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarAvionActionPerformed(evt);
            }
        });

        btEditarAvion.setText("Editar Avión");

        btEliminarAvion.setText("Eliminar Avión");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(42, 42, 42)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbEstadoAvion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textImprontaAvion)
                    .addComponent(textPasajerosAvion)
                    .addComponent(textCantidadCombustibleAvion)
                    .addComponent(cbTipoCombustibleAvion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btConsultarAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEditarAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEliminarAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCrearAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textImprontaAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCrearAvion))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textPasajerosAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultarAvion))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textCantidadCombustibleAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditarAvion))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbEstadoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminarAvion))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbTipoCombustibleAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Avión", panel3);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Automóvil", panel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCantidadCombustibleVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCantidadCombustibleVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCantidadCombustibleVehiculoActionPerformed

    private void btCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearVehiculoActionPerformed
        // TODO add your handling code here:
        //clsAvion avion = new clsAvion("Gasolina Avion", 100, 500, "HFGJJ4325", "averiado");
        //vehiculos.add(avion);
        try{
            String impronta_vehiculo = textImprontaVehiculo.getText();
            int pasajeros_vehiculo = Integer.parseInt(textPasajerosVehiculo.getText());
            int cantidad_combustible = Integer.parseInt(textCantidadCombustibleVehiculo.getText());
            String estado_vehiculo = cbEstadoVehiculo.getSelectedItem().toString();
        
            clsVehiculo vehiculo = new clsVehiculo(pasajeros_vehiculo, cantidad_combustible,impronta_vehiculo , estado_vehiculo);
            vehiculos.add(vehiculo);
            
            Llenar_Lista();
            
            Limpiar_formulario();
            
            JOptionPane.showMessageDialog(this,"Se instancio el vehículo con impronta: " + vehiculo.getImpronta_chasis());
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Corrija los datos ingresados.");
        }
        
    }//GEN-LAST:event_btCrearVehiculoActionPerformed

    private void btConsultarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarVehiculoActionPerformed
        // TODO add your handling code here:
        String impronta_vehiculo = textImprontaVehiculo.getText();
        boolean encontrado=false;
        for (clsVehiculo vehiculo: vehiculos){
            if (vehiculo.getImpronta_chasis().equals(impronta_vehiculo)){
                //textCantidadCombustibleVehiculo.setText(vehiculo.getCombustible()+"");
                //textPasajerosVehiculo.setText(vehiculo.getPasajeros()+"");
                //cbEstadoVehiculo.setSelectedItem(vehiculo.getEstado_vehiculo());
                this.Limpiar_formulario();
                JOptionPane.showMessageDialog(this,"El vehiculo con chasis: " 
                        + vehiculo.getImpronta_chasis() + "\n"
                +"Cantidad combustible: " + vehiculo.getCombustible()+"\n"+
                        "Pasajeros: " + vehiculo.getPasajeros()+"\n"+
                        "Estado Vehículo: " +vehiculo.getEstado_vehiculo());
                encontrado = true;
                break;
            }
        }
        
        if (encontrado==false){
            JOptionPane.showMessageDialog(this, "Vehículo no encontrado");
        }
        
    }//GEN-LAST:event_btConsultarVehiculoActionPerformed

    private void btEditarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarVehiculoActionPerformed
        // TODO add your handling code here:
        String impronta_vehiculo = textImprontaVehiculo.getText();
        boolean encontrado=false;
        for (clsVehiculo vehiculo: vehiculos){
            if (vehiculo.getImpronta_chasis().equals(impronta_vehiculo)){
                vehiculo.setCombustible(Integer.parseInt(textCantidadCombustibleVehiculo.getText()));
                vehiculo.setPasajeros(Integer.parseInt(textPasajerosVehiculo.getText()));
                vehiculo.setEstado_vehiculo(cbEstadoVehiculo.getSelectedItem().toString());
                this.Limpiar_formulario();
                this.Llenar_Lista();
                JOptionPane.showMessageDialog(this, "El vehiculo con chasis: " 
                        + vehiculo.getImpronta_chasis() + " fue actualizado");
                encontrado = true;
                break;
            }
        }
        
        if (encontrado==false){
            JOptionPane.showMessageDialog(this, "Vehículo no encontrado");
        }
        
        
    }//GEN-LAST:event_btEditarVehiculoActionPerformed

    private void btEliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarVehiculoActionPerformed
        // TODO add your handling code here:
                String impronta_vehiculo = textImprontaVehiculo.getText();
        boolean encontrado=false;
        for (clsVehiculo vehiculo: vehiculos){
            if (vehiculo.getImpronta_chasis().equals(impronta_vehiculo)){
                this.vehiculos.remove(vehiculo);
                this.Limpiar_formulario();
                this.Llenar_Lista();
                JOptionPane.showMessageDialog(this, "El vehiculo con chasis: " 
                        + vehiculo.getImpronta_chasis() + " fue eliminado");
                encontrado = true;
                break;
            }
        }
        
        if (encontrado==false){
            JOptionPane.showMessageDialog(this, "Vehículo no encontrado");
        }
    }//GEN-LAST:event_btEliminarVehiculoActionPerformed

    private void textImprontaAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textImprontaAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textImprontaAvionActionPerformed

    private void btCrearAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearAvionActionPerformed
        // TODO add your handling code here:
        try{
            String impronta_chasis_avion = textImprontaAvion.getText();
            int pasajeros_avion = Integer.parseInt(textPasajerosAvion.getText());
            int cantidad_combustible_avion = Integer.parseInt(textCantidadCombustibleAvion.getText());
            String estado_avion = cbEstadoAvion.getSelectedItem().toString();
            String tipo_combustible_avion = cbTipoCombustibleAvion.getSelectedItem().toString();
            
            clsAvion avion = new clsAvion(tipo_combustible_avion, pasajeros_avion, cantidad_combustible_avion, impronta_chasis_avion, estado_avion);
            vehiculos.add(avion);//polimorfismo puro
            
            this.Llenar_Lista();
            
            JOptionPane.showMessageDialog(this, "Se creó el avión con impronta: " + avion.getImpronta_chasis() + " y tipo combustible: " + avion.getTipo_combustible());
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Revise datos. No es posible crear un avión con  la información suministrada");
        }
        
    }//GEN-LAST:event_btCrearAvionActionPerformed

    private void btConsultarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarAvionActionPerformed
        // TODO add your handling code here:
        String impronta_chasis = textImprontaAvion.getText();      
        clsAvion avion = (clsAvion) ctrlVehiculo.ConsultarVehiculo(impronta_chasis,"Pasajeros en vuelo");
        if (avion==null){
            JOptionPane.showMessageDialog(this, "Avion no encontrado");
        } else{
            textPasajerosAvion.setText(avion.getPasajeros()+"");
            textCantidadCombustibleAvion.setText(avion.getCombustible()+"");
            cbEstadoAvion.setSelectedItem(avion.getEstado_vehiculo());
            cbTipoCombustibleAvion.setSelectedItem(avion.getTipo_combustible());
        }
        
        
        
    }//GEN-LAST:event_btConsultarAvionActionPerformed

    
    private void Llenar_Lista(){
        DefaultListModel model = new DefaultListModel();
        int index=0;
        for (clsVehiculo vehiculo : vehiculos){
            if (vehiculo.Tipo_de_Transporte().equals("Pasajeros en vuelo")){
                clsAvion avion = (clsAvion) vehiculo;
                String datos = vehiculo.getImpronta_chasis()+ " - " + vehiculo.getPasajeros() + " - " + vehiculo.getCombustible() + " - " +vehiculo.getEstado_vehiculo() + " - "+ avion.getTipo_combustible();
                model.add(index, datos);
                index ++;  
            }else if(vehiculo.Tipo_de_Transporte().equals("Pasajeros en vehiculo terrestre")){
                clsAutomovil automovil = (clsAutomovil) vehiculo;
                String datos = vehiculo.getImpronta_chasis()+ " - " + vehiculo.getPasajeros() + " - " + vehiculo.getCombustible() + " - " +vehiculo.getEstado_vehiculo() + " - "+ automovil.getTipo_combustible();
                model.add(index, datos);
                index ++;  
            }else{            
                String datos = vehiculo.getImpronta_chasis()+ " - " + vehiculo.getPasajeros() + " - " + vehiculo.getCombustible() + " - " +vehiculo.getEstado_vehiculo();
                model.add(index, datos);
                index ++;
            }
        }
        lsListaVehiculos.setModel(model);
    }
    
    private void Limpiar_formulario(){
        textImprontaVehiculo.setText("");
        textPasajerosVehiculo.setText("");
        textCantidadCombustibleVehiculo.setText("");
        cbEstadoVehiculo.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarAvion;
    private javax.swing.JButton btConsultarVehiculo;
    private javax.swing.JButton btCrearAvion;
    private javax.swing.JButton btCrearVehiculo;
    private javax.swing.JButton btEditarAvion;
    private javax.swing.JButton btEditarVehiculo;
    private javax.swing.JButton btEliminarAvion;
    private javax.swing.JButton btEliminarVehiculo;
    private javax.swing.JComboBox<String> cbEstadoAvion;
    private javax.swing.JComboBox<String> cbEstadoVehiculo;
    private javax.swing.JComboBox<String> cbTipoCombustibleAvion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lsListaVehiculos;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private javax.swing.JTextField textCantidadCombustibleAvion;
    private javax.swing.JTextField textCantidadCombustibleVehiculo;
    private javax.swing.JTextField textImprontaAvion;
    private javax.swing.JTextField textImprontaVehiculo;
    private javax.swing.JTextField textPasajerosAvion;
    private javax.swing.JTextField textPasajerosVehiculo;
    // End of variables declaration//GEN-END:variables
}
