/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import classes.clsAutomovil;
import classes.clsAvion;
import classes.clsVehiculo;
import controlador.ctrlVehiculo;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author andres
 */
public class AdministradorVehiculos extends javax.swing.JFrame {
    ctrlVehiculo ctrlVehiculo;
    LinkedList<clsVehiculo> vehiculos = new LinkedList<>();
     
    /**
     * Creates new form AdministradorVehiculos
     */
    public AdministradorVehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsListaVehiculos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbEstadoVehiculo = new javax.swing.JComboBox<>();
        txtCantidadCombustibleVehiculo = new javax.swing.JTextField();
        txtPasajerosVehiculo = new javax.swing.JTextField();
        txtImprontaVehiculo = new javax.swing.JTextField();
        btConsultarVehiculo = new javax.swing.JButton();
        btEditarVehiculo1 = new javax.swing.JButton();
        btCrearVehiculo = new javax.swing.JButton();
        btEliminarVehiculo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtImprontaAvion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPasajerosAvion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCantidadCombustibleAvion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbEstadoAvion = new javax.swing.JComboBox<>();
        btCrearAvion = new javax.swing.JButton();
        btConsultarAvion = new javax.swing.JButton();
        btEliminarAvion = new javax.swing.JButton();
        btEditarAvion = new javax.swing.JButton();
        cbTipoCombustibleAvion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("Administrador de Vehiculos");

        jLabel1.setText("Vehiculos Existentes");

        lsListaVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lsListaVehiculos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lista de Vehiculos", jPanel1);

        jLabel2.setText("Pasajeros");

        jLabel3.setText("Impronta");

        jLabel4.setText("Cantidad de Combustible");

        jLabel6.setText("Estado del Vehiculo");

        cbEstadoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En Funcionamiento", "Averiado", "Reparado", "En manteminiento" }));

        btConsultarVehiculo.setText("Consultar Vehiculo");
        btConsultarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarVehiculoActionPerformed(evt);
            }
        });

        btEditarVehiculo1.setText("Editar Vehiculo");
        btEditarVehiculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarVehiculo1ActionPerformed(evt);
            }
        });

        btCrearVehiculo.setText("Crear Vehiculo");
        btCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearVehiculoActionPerformed(evt);
            }
        });

        btEliminarVehiculo.setText("Eliminar Vehiculo");
        btEliminarVehiculo.setToolTipText("");
        btEliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidadCombustibleVehiculo)
                                    .addComponent(txtPasajerosVehiculo)
                                    .addComponent(txtImprontaVehiculo)
                                    .addComponent(cbEstadoVehiculo, 0, 180, Short.MAX_VALUE))
                                .addGap(29, 29, 29))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btEliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btEditarVehiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btConsultarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImprontaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPasajerosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCantidadCombustibleVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(cbEstadoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditarVehiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Vehiculos", jPanel2);

        jLabel5.setText("Impronta");

        jLabel7.setText("Pasajeros");

        jLabel8.setText("Cantidad de Combustible");

        jLabel9.setText("Estado del Vehiculo");

        cbEstadoAvion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En Funcionamiento", "Averiado", "Reparado", "En manteminiento" }));

        btCrearAvion.setText("Crear Avion");
        btCrearAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearAvionActionPerformed(evt);
            }
        });

        btConsultarAvion.setText("Consultar Avion");
        btConsultarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarAvionActionPerformed(evt);
            }
        });

        btEliminarAvion.setText("Eliminar Avion");
        btEliminarAvion.setToolTipText("");
        btEliminarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarAvionActionPerformed(evt);
            }
        });

        btEditarAvion.setText("Editar Avion");
        btEditarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarAvionActionPerformed(evt);
            }
        });

        cbTipoCombustibleAvion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina 100", "Gasolina 130" }));

        jLabel10.setText("Tipo Combustible");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addComponent(btCrearAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConsultarAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadCombustibleAvion)
                            .addComponent(txtPasajerosAvion)
                            .addComponent(txtImprontaAvion)
                            .addComponent(cbEstadoAvion, 0, 180, Short.MAX_VALUE)
                            .addComponent(cbTipoCombustibleAvion, 0, 180, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btEliminarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEditarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImprontaAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPasajerosAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCantidadCombustibleAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(cbEstadoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTipoCombustibleAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCrearAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Aviones", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Automoviles", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearVehiculoActionPerformed
        try{
        String improntaVehiculo = txtImprontaVehiculo.getText();
        int pasajeros = Integer.parseInt(txtPasajerosVehiculo.getText());
        int cantidadCombustible = Integer.parseInt(txtCantidadCombustibleVehiculo.getText());
        String estadoVehiculo = cbEstadoVehiculo.getSelectedItem().toString();
        
        clsVehiculo vehiculo = new clsVehiculo(pasajeros,cantidadCombustible,improntaVehiculo,estadoVehiculo);
            
        vehiculos.add(vehiculo);
        
        Llenar_Lista();     
        Limpiar_formulario();
        JOptionPane.showMessageDialog(this, "Se instancio el vehiculo con la impronta: " + vehiculo.getImpronta_chasis()); 
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Corrija los datos ingresados.");
        }
    }//GEN-LAST:event_btCrearVehiculoActionPerformed

    private void btConsultarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarVehiculoActionPerformed
        String impronta_vehiculo = txtImprontaVehiculo.getText();
        boolean encontrado=false;
        for (clsVehiculo vehiculo: vehiculos){
            if (vehiculo.getImpronta_chasis().equals(impronta_vehiculo)){
                this.Limpiar_formulario();
                JOptionPane.showMessageDialog(this,"El vehiculo con chasis: " 
                        + vehiculo.getImpronta_chasis() + "\n"
                +"Cantidad combustible: " + vehiculo.getCombustible()+"\n"+
                        "Pasajeros: " + vehiculo.getPasajeros()+"\n"+
                        "Estado Vehículo: " +vehiculo.getEstado_vehiculo());
                encontrado = true;
                break;
            }
        }
        
        if (encontrado==false){
            JOptionPane.showMessageDialog(this, "Vehículo no encontrado");
        }
    }//GEN-LAST:event_btConsultarVehiculoActionPerformed

    private void btEditarVehiculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarVehiculo1ActionPerformed
        String improntaVehiculo = txtImprontaVehiculo.getText();
        boolean encontrado=false;
        for (clsVehiculo vehiculo: vehiculos){
            if (vehiculo.getImpronta_chasis().equals(improntaVehiculo)){
                vehiculo.setCombustible(Integer.parseInt(txtCantidadCombustibleVehiculo.getText()));
                vehiculo.setPasajeros(Integer.parseInt(txtPasajerosVehiculo.getText()));
                vehiculo.setEstado_vehiculo(cbEstadoVehiculo.getSelectedItem().toString());
                this.Limpiar_formulario();
                this.Llenar_Lista();
                JOptionPane.showMessageDialog(this, "El vehiculo con chasis: " 
                        + vehiculo.getImpronta_chasis() + " fue actualizado");
                encontrado = true;
                break;
            }
        }
        
        if (encontrado==false){
            JOptionPane.showMessageDialog(this, "Vehículo no encontrado");
        }        
    }//GEN-LAST:event_btEditarVehiculo1ActionPerformed

    private void btEliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarVehiculoActionPerformed
        String improntaVehiculo = txtImprontaVehiculo.getText();
        boolean encontrado=false;
        for (clsVehiculo vehiculo: vehiculos){
            if (vehiculo.getImpronta_chasis().equals(improntaVehiculo)){
                this.vehiculos.remove(vehiculo);
                this.Limpiar_formulario();
                this.Llenar_Lista();
                JOptionPane.showMessageDialog(this, "El vehiculo con chasis: " 
                        + vehiculo.getImpronta_chasis() + " fue eliminado");
                encontrado = true;
                break;
            }
        }
        
        if (encontrado==false){
            JOptionPane.showMessageDialog(this, "Vehículo no encontrado");
        }
    }//GEN-LAST:event_btEliminarVehiculoActionPerformed

    private void btCrearAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearAvionActionPerformed
         try{
            String improntaChasisAvion = txtImprontaAvion.getText();
            int pasajerosAvion = Integer.parseInt(txtPasajerosAvion.getText());
            int cantidadCombustible_avion = Integer.parseInt(txtCantidadCombustibleAvion.getText());
            String estadoAvion = cbEstadoAvion.getSelectedItem().toString();
            String tipoCombustibleAvion = cbTipoCombustibleAvion.getSelectedItem().toString();
            
            clsAvion avion = new clsAvion(tipoCombustibleAvion, pasajerosAvion, cantidadCombustible_avion, improntaChasisAvion, estadoAvion);
            vehiculos.add(avion);//polimorfismo puro
            
            this.Llenar_Lista();
            
            JOptionPane.showMessageDialog(this, "Se creó el avión con impronta: " + avion.getImpronta_chasis() + " y tipo combustible: " + avion.getTipo_combustible());
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Revise datos. No es posible crear un avión con  la información suministrada");
        }
    }//GEN-LAST:event_btCrearAvionActionPerformed

    private void btConsultarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarAvionActionPerformed
        String impronta_chasis = txtImprontaAvion.getText();      
        clsAvion avion = (clsAvion) ctrlVehiculo.ConsultarVehiculo(impronta_chasis,"Pasajeros en vuelo");
        if (avion==null){
            JOptionPane.showMessageDialog(this, "Avion no encontrado");
        } else{
            txtPasajerosAvion.setText(avion.getPasajeros()+"");
            txtCantidadCombustibleAvion.setText(avion.getCombustible()+"");
            cbEstadoAvion.setSelectedItem(avion.getEstado_vehiculo());
            cbTipoCombustibleAvion.setSelectedItem(avion.getTipo_combustible());
        }
        
        
    }//GEN-LAST:event_btConsultarAvionActionPerformed

    private void btEliminarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEliminarAvionActionPerformed

    private void btEditarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditarAvionActionPerformed

    private void Llenar_Lista(){
        DefaultListModel model = new DefaultListModel();
        int index=0;
        for (clsVehiculo vehiculo : vehiculos){
            if (vehiculo.tipoDeTransporte().equals("Pasajeros en vuelo")){
                clsAvion avion = (clsAvion) vehiculo;
                String datos = vehiculo.getImpronta_chasis()+ " - " + vehiculo.getPasajeros() + " - " + vehiculo.getCombustible() + " - " +vehiculo.getEstado_vehiculo() + " - "+ avion.getTipo_combustible();
                model.add(index, datos);
                index ++;  
            }else if(vehiculo.tipoDeTransporte().equals("Pasajeros en vehiculo terrestre")){
                clsAutomovil automovil = (clsAutomovil) vehiculo;
                String datos = vehiculo.getImpronta_chasis()+ " - " + vehiculo.getPasajeros() + " - " + vehiculo.getCombustible() + " - " +vehiculo.getEstado_vehiculo() + " - "+ automovil.getTipo_combustible();
                model.add(index, datos);
                index ++;  
            }else{            
                String datos = vehiculo.getImpronta_chasis()+ " - " + vehiculo.getPasajeros() + " - " + vehiculo.getCombustible() + " - " +vehiculo.getEstado_vehiculo();
                model.add(index, datos);
                index ++;
            }
        }
        lsListaVehiculos.setModel(model);
    }
    
    private void Limpiar_formulario(){
        txtImprontaVehiculo.setText("");
        txtPasajerosVehiculo.setText("");
        txtCantidadCombustibleVehiculo.setText("");
        cbEstadoVehiculo.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarAvion;
    private javax.swing.JButton btConsultarVehiculo;
    private javax.swing.JButton btCrearAvion;
    private javax.swing.JButton btCrearVehiculo;
    private javax.swing.JButton btEditarAvion;
    private javax.swing.JButton btEditarVehiculo1;
    private javax.swing.JButton btEliminarAvion;
    private javax.swing.JButton btEliminarVehiculo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbEstadoAvion;
    private javax.swing.JComboBox<String> cbEstadoVehiculo;
    private javax.swing.JComboBox<String> cbTipoCombustibleAvion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.Label label1;
    private javax.swing.JList<String> lsListaVehiculos;
    private javax.swing.JTextField txtCantidadCombustibleAvion;
    private javax.swing.JTextField txtCantidadCombustibleVehiculo;
    private javax.swing.JTextField txtImprontaAvion;
    private javax.swing.JTextField txtImprontaVehiculo;
    private javax.swing.JTextField txtPasajerosAvion;
    private javax.swing.JTextField txtPasajerosVehiculo;
    // End of variables declaration//GEN-END:variables
}
